### ISSUE TITLE
Move data capability should be toggleable with a paramater

### ISSUE THREAD

**Issue by ChristSent** [ChristSent/OnedriveRoamingProfile#3]
The existing local files should be optional to move to the newly redirected folder location (the OneDrive location).

In other words, there could be times when the existing files in Documents, Desktop, etc, are not needed or wanted in the OneDrive sync folders. Only newly added files would be synced.

**Comment by cmoneycode** [comment]
Added the $moveContent paramater to accept "yes" or "no".
